export enum FocusSessionErrorCode {
  SESSION_CAP_REACHED = "SESSION_CAP_REACHED",
  SESSION_TIME_LIMIT_REACHED = "SESSION_TIME_LIMIT_REACHED",
  SESSION_ALREADY_ACTIVE = "SESSION_ALREADY_ACTIVE",
  SESSION_TIMELINE_REQUIRES_PRO = "SESSION_TIMELINE_REQUIRES_PRO",
}
